// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	CostumerId           int32        `protobuf:"varint,1,opt,name=costumer_id,json=costumerId,proto3" json:"costumer_id,omitempty"`
	OrderItems           []*OrderItem `protobuf:"bytes,2,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	TotalPrice           float32      `protobuf:"fixed32,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetCostumerId() int32 {
	if m != nil {
		return m.CostumerId
	}
	return 0
}

func (m *CreateOrderRequest) GetOrderItems() []*OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *CreateOrderRequest) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

type OrderItem struct {
	ProductCode          string   `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{1}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateOrderResponse struct {
	OrderId              int32    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{2}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "CreateOrderRequest")
	proto.RegisterType((*OrderItem)(nil), "OrderItem")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
}

func init() {
	proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed)
}

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0xed, 0xc6, 0xe6, 0xf6, 0xea, 0xc5, 0xcc, 0xc3, 0x1c, 0x88, 0xb3, 0xa7, 0x81, 0xd8,
	0x8e, 0x89, 0x57, 0x0f, 0xee, 0x34, 0x11, 0x94, 0x1e, 0xbd, 0x94, 0x2c, 0x79, 0xcc, 0xc0, 0xda,
	0xd7, 0x25, 0x2f, 0x82, 0x67, 0xff, 0x71, 0x69, 0xb6, 0x0e, 0x44, 0x2f, 0x21, 0xf9, 0xc8, 0xfb,
	0x1e, 0xbf, 0xf7, 0xe0, 0x9c, 0xac, 0x46, 0x9b, 0x85, 0x33, 0xad, 0x2d, 0x31, 0x25, 0xdf, 0x11,
	0x88, 0xa5, 0x45, 0xc9, 0xf8, 0xda, 0xd0, 0x1c, 0x77, 0x1e, 0x1d, 0x8b, 0x6b, 0x88, 0x15, 0x39,
	0xf6, 0x25, 0xda, 0xc2, 0xe8, 0x71, 0x34, 0x8d, 0x66, 0xbd, 0x1c, 0x5a, 0xb4, 0xd2, 0xe2, 0x16,
	0xe2, 0xa0, 0x29, 0x0c, 0x63, 0xe9, 0xc6, 0x9d, 0x69, 0x77, 0x16, 0x2f, 0x20, 0x0d, 0x92, 0x15,
	0x63, 0x99, 0x03, 0xb5, 0x57, 0xd7, 0xd8, 0x98, 0x58, 0x6e, 0x8b, 0xda, 0x1a, 0x85, 0xe3, 0xee,
	0x34, 0x9a, 0x75, 0x72, 0x08, 0xe8, 0xad, 0x21, 0x89, 0x81, 0xe1, 0xb1, 0x52, 0xdc, 0xc0, 0x59,
	0x6d, 0x49, 0x7b, 0xc5, 0x85, 0x22, 0x8d, 0xa1, 0xf9, 0x30, 0x8f, 0x0f, 0x6c, 0x49, 0x1a, 0xc5,
	0x15, 0x80, 0xaf, 0x0c, 0x1f, 0x7c, 0x9d, 0xe0, 0x1b, 0x36, 0x24, 0xe8, 0xc4, 0x04, 0x06, 0x3b,
	0x2f, 0x2b, 0x36, 0xfc, 0x15, 0x9a, 0xf5, 0xf2, 0xe3, 0x3b, 0x99, 0xc3, 0xe8, 0x57, 0x5e, 0x57,
	0x53, 0xe5, 0x50, 0x5c, 0xc2, 0xe0, 0x90, 0xa7, 0x4d, 0x7b, 0xba, 0x0f, 0xa0, 0x17, 0x8f, 0xd0,
	0x0b, 0x7f, 0xc5, 0x03, 0xf4, 0xf7, 0xa5, 0x62, 0x94, 0xfe, 0x9d, 0xd9, 0xe4, 0x22, 0xfd, 0x47,
	0x9c, 0x9c, 0x3c, 0x2d, 0xde, 0xe7, 0x1b, 0xc3, 0x1f, 0x7e, 0x9d, 0xbd, 0x78, 0x25, 0xdd, 0xb3,
	0xf4, 0x3a, 0x2b, 0x8d, 0xb2, 0xe4, 0xd0, 0x7e, 0x1a, 0x85, 0x77, 0x61, 0x13, 0xd9, 0x86, 0xb6,
	0xb2, 0xda, 0xec, 0x97, 0xb3, 0xee, 0x07, 0x76, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x71, 0xe5,
	0x22, 0xfa, 0xb2, 0x01, 0x00, 0x00,
}
